core/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('datos/', Datos.as_view(), name='datos'),
    path('deudores/', DeudorListView.as_view(), name='deudor-list'),
    path('deudores/<int:pk>/', DeudorDetailView.as_view(), name='deudor-detail'),
    path('deudores/nuevo/', DeudorCreateView.as_view(), name='deudor-create'),
    path('deudores/<int:pk>/editar/', DeudorUpdateView.as_view(), name='deudor-update'),
    path('deudores/<int:pk>/eliminar/', DeudorDeleteView.as_view(), name='deudor-delete'),
    path('pagos/', PagoListView.as_view(), name='pago-list'),
    path('pagos-grupo/<int:deudor>/<int:anio>/<int:quincena>/', PagoListViewGpo.as_view(), name='pagos-grupo'), 
    path('pagos/<int:pk>/', PagoDetailView.as_view(), name='pago-detail'),
    path('pagos/nuevo/', PagoCreateView.as_view(), name='pago-create'),
    path('pagos/<int:pk>/editar/', PagoUpdateView.as_view(), name='pago-update'),
    path('pagos/<int:pk>/eliminar/', PagoDeleteView.as_view(), name='pago-delete'),
    path('crear_pagos/', CrearPagosView.as_view(), name='crear_pagos'),
    path('cobros/', CobroListView.as_view(), name='cobro-list'),
    path('cobros/<int:pk>/', CobroDetailView.as_view(), name='cobro-detail'),
    path('cobros/nuevo/', CobroCreateView.as_view(), name='cobro-create'),
    path('cobros/<int:pk>/editar/', CobroUpdateView.as_view(), name='cobro-update'),
    path('cobros/<int:pk>/eliminar/', CobroDeleteView.as_view(), name='cobro-delete'),
    path('crear_cobros/', CrearCobrosView.as_view(), name='crear_cobros'),
    path('sobrantes/', SobranteListView.as_view(), name='sobrante-list'),
    path('sobrantes/<int:pk>/', SobranteDetailView.as_view(), name='sobrante-detail'),
    path('sobrantes/nuevo/', SobranteCreateView.as_view(), name='sobrante-create'),
    path('sobrantes/<int:pk>/editar/', SobranteUpdateView.as_view(), name='sobrante-update'),
    path('sobrantes/<int:pk>/eliminar/', SobranteDeleteView.as_view(), name='sobrante-delete'),
]

core/models.py
from django.db import models
from django.contrib.auth.mixins import PermissionRequiredMixin

ANIOS = (
    (0, ''),
    (2024, '2024'),
    (2025, '2025'),
    (2026, '2026'),
    (2027, '2027'),
    (2028, '2028'),
    (2029, '2029'),
    (2030, '2030'),
)
ESTATUS_COBROS = (
    (0, 'Pendiente'),
    (1, 'Recibido'),
)
ESTATUS_PAGAR = (
    (0, 'Baja'),
    (1, 'Activo'),
)
ESTATUS_PAGOS = (
    (0, 'Pendiente'),
    (1, 'Pagado'),
    (2, 'Cancelado'),
)
QUINCENAS = (
    (0, ''),
    (1, '1a. qna.'),
    (2, '2a. qna.'),
    (3, '3a. qna.'),
    (4, '4a. qna.'),
    (5, '5a. qna.'),
    (6, '6a. qna.'),
    (7, '7a. qna.'),
    (8, '8a. qna.'),
    (9, '9a. qna.'),
    (10, '10a. qna.'),
    (11, '11a. qna.'),
    (12, '12a. qna.'),
    (13, '13a. qna.'),
    (14, '14a. qna.'),
    (15, '15a. qna.'),
    (16, '16a. qna.'),
    (17, '17a. qna.'),
    (18, '18a. qna.'),
    (19, '19a. qna.'),
    (20, '20a. qna.'),
    (21, '21a. qna.'),
    (22, '22a. qna.'),
    (23, '23a. qna.'),
    (24, '24a. qna.'),
)
TIPO_PAGO = (
    ('Q', 'Quincena'),
    ('M', 'Mensual'),
    ('B', 'Bimestral'),
    ('S', 'Semestral'),
)

# Create your models here.

class Deudor(models.Model, PermissionRequiredMixin):
    nombre = models.CharField('Nombre', max_length=80)
    corte = models.DecimalField('Corte', max_digits=2, decimal_places=0, default=1)
    tipo_pago = models.CharField('Tipo pago', max_length=1, choices=TIPO_PAGO, default='Q')
    qna_empieza = models.IntegerField('Qna empieza', choices=QUINCENAS, default=1)
    anio_empieza = models.IntegerField('Año empieza', choices=ANIOS, default=2024)
    qna_termina = models.IntegerField('Qna termina', choices=QUINCENAS, default=0)
    anio_termina = models.IntegerField('Año termina', choices=ANIOS, default=0)
    estatus = models.IntegerField('Estatus', choices=ESTATUS_PAGAR, default=1)
    created = models.DateTimeField("Creado", auto_now_add=True)
    modified = models.DateTimeField("Actualizado", auto_now=True)
    
    class Meta:
        verbose_name = 'Deudor'
        verbose_name_plural = 'Deudores'
        ordering = ['nombre',]
        unique_together = ['nombre']
        db_table = 'Deudor'

    def __str__(self):
        return '%s' % (self.nombre)

class Pago(models.Model, PermissionRequiredMixin):
    deudor = models.ForeignKey('Deudor', related_name='pago_deudor', on_delete=models.CASCADE)
    importe_pagar = models.DecimalField('Pagar', max_digits=8, decimal_places=2, default=0)
    importe_pagado = models.DecimalField('Pagado', max_digits=8, decimal_places=2, default=0)
    qna_pagar = models.IntegerField('Qna. pagar', choices=QUINCENAS, default=1)
    anio_pagar = models.IntegerField('Año pagar', choices=ANIOS, default=2024)
    comentario = models.CharField('Comentario', max_length=256, blank=True, null=True)
    fecha_pagado = models.DateField("Fecha pagado", blank=True, null=True)
    estatus = models.IntegerField('Estatus', choices=ESTATUS_PAGOS, default=0)
    created = models.DateTimeField("Creado", auto_now_add=True)
    modified = models.DateTimeField("Actualizado", auto_now=True)
    
    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'
        ordering = ['deudor','anio_pagar','qna_pagar']
        db_table = 'Pago'

    def __str__(self):
        return '%s' % (self.deudor, self.anio_pagar, self.qna_pagar)

class Cobro(models.Model, PermissionRequiredMixin):
    importe_cobro = models.DecimalField('Cobrar', max_digits=8, decimal_places=2, default=0)
    importe_recibido = models.DecimalField('Recibido', max_digits=8, decimal_places=2, default=0)
    qna_cobro = models.IntegerField('Qna. cobro', choices=QUINCENAS, default=1)
    anio_cobro = models.IntegerField('Año cobro', choices=ANIOS, default=2024)
    comentario = models.CharField('Comentario', max_length=256, blank=True, null=True)
    fecha_cobro = models.DateField("Fecha cobro", blank=True, null=True)
    estatus = models.IntegerField('Estatus', choices=ESTATUS_COBROS, default=0)
    created = models.DateTimeField("Creado", auto_now_add=True)
    modified = models.DateTimeField("Actualizado", auto_now=True)
    
    class Meta:
        verbose_name = 'Cobro'
        verbose_name_plural = 'Cobros'
        ordering = ['anio_cobro','qna_cobro','id']
        db_table = 'Cobro'

    def __str__(self):
        return '%s' % (self.comentario, self.anio_cobro, self.qna_cobro, importe_recibido)

class Sobrante(models.Model, PermissionRequiredMixin):
    importe_sobrante = models.DecimalField('Sobrante', max_digits=8, decimal_places=2, default=0)
    qna_sobrante = models.IntegerField('Qna. sobrante', choices=QUINCENAS, default=1)
    anio_sobrante = models.IntegerField('Año sobrante', choices=ANIOS, default=2024)
    comentario = models.CharField('Comentario', max_length=256, blank=True, null=True)
    created = models.DateTimeField("Creado", auto_now_add=True)
    modified = models.DateTimeField("Actualizado", auto_now=True)
    
    class Meta:
        verbose_name = 'Sobrante'
        verbose_name_plural = 'Sobrantes'
        ordering = ['anio_sobrante','qna_sobrante']
        unique_together = ['anio_sobrante','qna_sobrante']
        db_table = 'Sobrante'

    def __str__(self):
        return '%s' % (self.anio_sobrante, self.qna_sobrante, importe_sobrante)

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views import View
from django.http import JsonResponse
from decimal import Decimal
from django.views.generic.edit import FormView


from .models import *
from .forms import *

class QnaContenido:
    def __init__(self, nombre='', estatus=0, importe=Decimal('0.00'), 
        fecha='', id=0, cantidad=0, quincena=0, anio=0, id_deudor=0):
        self.nombre = nombre
        self.estatus = estatus
        self.importe = importe
        self.fecha = fecha
        self.id = id
        self.cantidad = cantidad
        self.quincena = quincena
        self.anio = anio
        self.id_deudor = id_deudor

def arma_matriz(request, anio):

    deudores_matriz_encabezado = []
    deudores_matriz_contenido = []
    deudores_matriz_total_gasto = []
    deudores_matriz_total_cobro = []
    deudores_matriz_saldo = []
    deudores_matriz_saldo_anterior = []
    deudores_matriz_saldo_actual = []
    deudores_indice = []

    # Encabezado de la matriz
    encabezado = ['Deudor', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre', 'Total']
    deudores_matriz_encabezado.append(encabezado)

    # Encabezado de las Qnas
    qnas_encabezado = ['1a Qna', '2a Qna'] * 12

    # Contenido celdas
    qnas_contenido1 = [Decimal('0.00').quantize(Decimal(f'1e-{2}')) for _ in range(25)]

    consecutivo = 0
    # Contenido de la matriz
    deudores = Deudor.objects.filter(estatus=1)
    for deudor in deudores:
        fila1 = [deudor.id, consecutivo]
        deudores_indice.append(fila1)
        consecutivo += 1
        qnas_contenido = [QnaContenido(nombre='',estatus=0, importe=Decimal('0.00'), \
            fecha='', id=0, cantidad=0, quincena=0, anio=0, id_deudor=0) for _ in range(24)]  # Lista de instancias QnaContenido
        fila = [deudor.nombre] + qnas_contenido + [Decimal('0.00').quantize(Decimal(f'1e-{2}'))]
        deudores_matriz_contenido.append(fila)

    renglon_total_gastos = consecutivo + 4

    # Contenido de la matriz total gasto
    fila = ['Total gasto'] + qnas_contenido1  # Agrega el total al final
    deudores_matriz_total_gasto.append(fila)

    # Contenido de la matriz total cobro
    fila = ['Total cobro'] + qnas_contenido1   # Agrega el total al final
    deudores_matriz_total_cobro.append(fila)

    # Contenido de la matriz total cobro
    fila = ['Sobrante mes anterior'] + qnas_contenido1   # Agrega el total al final
    deudores_matriz_saldo_anterior.append(fila)

    # Contenido de la matriz total cobro
    fila = ['Saldo'] + qnas_contenido1  # Agrega el total al final
    deudores_matriz_saldo.append(fila)

    # Contenido de la matriz total cobro
    fila = ['Saldo actual'] + qnas_contenido1  # Agrega el total al final
    deudores_matriz_saldo_actual.append(fila)

    pagos = Pago.objects.filter(anio_pagar=anio)

    for pago in pagos:
        fila = busca_deudor(pago.deudor.id, deudores_indice)
        columna = pago.qna_pagar
        if pago.importe_pagado > 0:
            importe = pago.importe_pagado
        else:
            importe = pago.importe_pagar
        
        deudores_matriz_contenido[fila][columna].importe += importe
        deudores_matriz_contenido[fila][columna].estatus = pago.estatus
        deudores_matriz_contenido[fila][columna].id = pago.id
        deudores_matriz_contenido[fila][columna].quincena = pago.qna_pagar
        deudores_matriz_contenido[fila][columna].nombre = pago.deudor.nombre
        deudores_matriz_contenido[fila][columna].anio = pago.anio_pagar
        deudores_matriz_contenido[fila][columna].cantidad += 1
        deudores_matriz_contenido[fila][columna].id_deudor = pago.deudor.id

        deudores_matriz_contenido[fila][25] += importe
        deudores_matriz_total_gasto[0][columna] += importe
        deudores_matriz_total_gasto[0][25] += importe
        


    cobros = Cobro.objects.filter(anio_cobro=anio)

    for cobro in cobros:
        columna = cobro.qna_cobro
        if cobro.importe_recibido > 0:
            importe = cobro.importe_recibido
        else:
            importe = cobro.importe_cobro

        deudores_matriz_total_cobro[0][columna] += importe
        deudores_matriz_total_cobro[0][25] += importe

        deudores_matriz_saldo[0][columna] = deudores_matriz_total_cobro[0][columna] - deudores_matriz_total_gasto[0][columna]

        deudores_matriz_saldo[0][25] = deudores_matriz_total_cobro[0][25] - deudores_matriz_total_gasto[0][25]

    saldo = Sobrante.objects.filter(anio_sobrante=anio, qna_sobrante=1).first()
    
    if saldo:
        saldo_inicial = saldo.importe_sobrante
    else:
        saldo_inicial = Decimal('0.00')

    deudores_matriz_saldo_anterior[0][1] = saldo_inicial

    for numero in range(1, 25):
        deudores_matriz_saldo_actual[0][numero] = deudores_matriz_saldo[0][numero] + deudores_matriz_saldo_anterior[0][numero]
        numero1 = numero + 1
        if numero < 24:
            deudores_matriz_saldo_anterior[0][numero1] += deudores_matriz_saldo_actual[0][numero]
    
    deudores_matriz_saldo_anterior[0][25] += saldo_inicial
    deudores_matriz_saldo_actual[0][25] = deudores_matriz_saldo[0][25] + deudores_matriz_saldo_anterior[0][25]

    context1 = {
        'deudores_matriz_encabezado': deudores_matriz_encabezado,
        'qnas_encabezado': qnas_encabezado,
        'deudores_matriz_contenido': deudores_matriz_contenido,
        'deudores_matriz_total_gasto': deudores_matriz_total_gasto,
        'deudores_matriz_total_cobro': deudores_matriz_total_cobro,
        'deudores_matriz_saldo_anterior': deudores_matriz_saldo_anterior,
        'deudores_matriz_saldo': deudores_matriz_saldo,
        'deudores_matriz_saldo_actual': deudores_matriz_saldo_actual,
        'anio': 'AÑO ' + str(anio),
    }

    tabla_cuerpo_html = render(request, 'core/tabla_cuerpo.html', context1).content.decode('utf-8')

    context = {
        'tabla_cuerpo_html': tabla_cuerpo_html
    }

    return context

def busca_deudor(id_buscar, deudores_indice):
    consecutivo_encontrado = None
    for fila in deudores_indice:
        if fila[0] == id_buscar:
            consecutivo_encontrado = fila[1]
            break
    return consecutivo_encontrado

class Index(View):
    template_name = 'core/index.html'
    def get(self, request, *args, **kwargs):
        selected_value = int(request.GET.get('selected_value', 2024))
        context = arma_matriz(request, selected_value)
        return render(request, self.template_name, context)

class Datos(View):
    def get(self, request, *args, **kwargs):
        selected_value = int(request.GET.get('selected_value'))
        context = arma_matriz(request, selected_value)
        return JsonResponse(context)

class DeudorListView(ListView):
    model = Deudor
    template_name = 'core/deudor_list.html'
    context_object_name = 'deudores'

class DeudorDetailView(DetailView):
    model = Deudor
    template_name = 'core/deudor_detail.html'
    context_object_name = 'deudor'

class DeudorCreateView(CreateView):
    model = Deudor
    template_name = 'core/deudor_form.html' 
    success_url = reverse_lazy('deudor-list')
    form_class = Deudor_form

class DeudorUpdateView(UpdateView):
    model = Deudor
    template_name = 'core/deudor_form.html'
    success_url = reverse_lazy('deudor-list')
    form_class = Deudor_form

class DeudorDeleteView(DeleteView):
    model = Deudor
    template_name = 'core/deudor_confirm_delete.html'
    success_url = reverse_lazy('deudor-list') 

class PagoListView(ListView):
    model = Pago
    template_name = 'core/pago_list.html'
    context_object_name = 'pagos'

class PagoListViewGpo(ListView):
    model = Pago
    template_name = 'core/pago_list.html'
    context_object_name = 'pagos'

    def get_queryset(self):
        deudor = self.kwargs.get('deudor',0)
        anio = self.kwargs.get('anio',0)
        quincena = self.kwargs.get('quincena',0)
        queryset = Pago.objects.filter(deudor__id=deudor, anio_pagar=anio, qna_pagar=quincena)
        return queryset

class PagoDetailView(DetailView):
    model = Pago
    template_name = 'core/pago_detail.html'
    context_object_name = 'pago'

class PagoCreateView(CreateView):
    model = Pago
    template_name = 'core/pago_form.html'
    success_url = reverse_lazy('pago-list')
    form_class = Pago_form

class PagoUpdateView(UpdateView):
    model = Pago
    template_name = 'core/pago_form.html'
    success_url = reverse_lazy('pago-list')
    form_class = Pago_form

class PagoDeleteView(DeleteView):
    model = Pago
    template_name = 'core/pago_confirm_delete.html'
    success_url = reverse_lazy('pago-list')

class CrearPagosView(FormView):
    template_name = 'core/pago_genera.html'
    form_class = PagoForm

    def form_valid(self, form):
        # Aquí puedes procesar y guardar los datos según tus necesidades
        desde_anio = form.cleaned_data['desde_anio']
        desde_quincena = form.cleaned_data['desde_quincena']
        hasta_anio = form.cleaned_data['hasta_anio']
        hasta_quincena = form.cleaned_data['hasta_quincena']
        deudor = form.cleaned_data['deudor']
        importe_pagar = form.cleaned_data['importe_pagar']
        comentario = form.cleaned_data['comentario']
        tipo_pagar = form.cleaned_data['tipo_pagar']

        # Recuperar el ID del deudor
        id_deudor = deudor.id

        print(f"ID del deudor: {id_deudor}")
        print(f"Desde año: {desde_anio}")
        print(f"Desde quincena: {desde_quincena}")
        print(f"Hasta año: {hasta_anio}")
        print(f"Hasta quincena: {hasta_quincena}")
        print(f"Importe a pagar: {importe_pagar}")
        print(f"Comentario: {comentario}")
        print(f"Como agregar: {tipo_pagar}")

        contador_qna = 1
        prende_sw = 0
        prende_sw_year = 0

core/templates/core/cobro_detail.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block headJS %}
{% endblock %}
{% block contenido %}
{% if user.is_authenticated %}
<div class="d-flex align-items-center justify-content-center">
    <div class="mt-2 mapa" style="padding: 10px; width: 450px">
        <h2>Detalles de Cobro</h2>
        <div class="row col-12">
            <div class="col-6">
                <div class="col-12">
                    Importe a Cobrar
                </div>
                <div class="col-12 form-control text-right">
                    {{cobro.importe_cobro}}
                </div>
            </div>
            <div class="col-6">
                <div class="col-12">
                    Importe recibido
                </div>
                <div class="col-12 form-control text-right">
                    {{cobro.importe_recibido}}
                </div>
            </div>
            <div class="col-6">
                <div class="col-12">
                    Año de cobro
                </div>
                <div class="col-12 form-control text-center">
                    {{cobro.get_anio_cobro_display}}
                </div>
            </div>
            <div class="col-6">
                <div class="col-12">
                    Quincena de cobro
                </div>
                <div class="col-12 form-control text-center">
                    {{cobro.get_qna_cobro_display}}
                </div>
            </div>
            <div class="col-12">
                <div class="col-12">
                    Comentario
                </div>
                <div class="col-12 form-control">
                    {{cobro.comentario|default_if_none:""}}
                </div>
            </div>
            <div class="col-8">
                <div class="col-12">
                    Fecha de cobro
                </div>
                <div class="col-12 form-control text-center">
                    {{cobro.fecha_cobro|default_if_none:""}}
                </div>
            </div>
            <div class="col-4">
                <div class="col-12">
                    Estatus
                </div>
                <div class="col-12 form-control text-center">
                    {{cobro.get_estatus_display}}
                </div>
            </div>
        </div>
        <div class="col-12 row mt-2">
            <div class="text-center col-3">
                <a class="btn btn-info" href="{% url 'cobro-update' pk=cobro.pk %}">Editar</a>
            </div>
            <div class="text-center col-3">
                <a class="btn btn-danger" href="{% url 'cobro-delete' pk=cobro.pk %}">Eliminar</a>
            </div>
            <div class="text-center col-6">
                <a class="btn btn-info" href="{% url 'cobro-list' %}">Volver a la lista</a>
            </div>
        </div>
    </div>
</div>
{% endif %}  
{% endblock %}

<script>
    {% block inicio %}
        $('.boton_4').addClass('active');
    {% endblock %}
</script>
    

core/templates/core/cobro_list.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block headJS %}
{% endblock %}
{% block contenido %}
{% if user.is_authenticated %}
<div class="mt-2 mapa" style="padding: 10px;">
  <h2>Lista de Cobros</h2>
  <a class="btn btn-info" href="{% url 'cobro-create' %}">Nuevo</a>
  <table class="table table-striped mt-2 text-center">
    <thead>
      <tr>
        <th class="col-1">Importe a Cobrar</th>
        <th class="col-1">Importe Recibido</th>
        <th class="col-1">Año Cobro</th>
        <th class="col-1">Qna. Cobro</th>
        <th class="col-3">Comentario</th>
        <th class="col-1">Fecha Cobro</th>
        <th class="col-1">Estatus</th>
        <th class="col-3">Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for cobro in cobros %}
        <tr>
          <td class="text-right">{{ cobro.importe_cobro }}</td>
          <td class="text-right">{{ cobro.importe_recibido }}</td>
          <td>{{ cobro.get_anio_cobro_display }}</td>
          <td>{{ cobro.get_qna_cobro_display }}</td>
          <td class="text-left">{{ cobro.comentario|default_if_none:"" }}</td>
          <td>{{ cobro.fecha_cobro|default_if_none:"" }}</td>
          <td>{{ cobro.get_estatus_display }}</td>
          <td>
            <a class="btn btn-info" href="{% url 'cobro-detail' pk=cobro.pk %}">Detalles</a>
            <a class="btn btn-info" href="{% url 'cobro-update' pk=cobro.pk %}">Editar</a>
            <a class="btn btn-danger" href="{% url 'cobro-delete' pk=cobro.pk %}">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}
{% endblock %}

<script>
    {% block inicio %}
        $('.boton_4').addClass('active');
    {% endblock %}
</script>
    

core/templates/core/deudor_detail.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block headJS %}
{% endblock %}
{% block contenido %}
{% if user.is_authenticated %}
<div class="d-flex align-items-center justify-content-center">
  <div class="mt-2 mapa" style="padding: 10px; width: 450px">
    <h2>Detalles de {{ deudor.nombre }}</h2>
    <div class="row col-12">
      Nombre
      <div class="col-12 form-control">
        {{deudor.nombre}}
      </div>
      <div class="col-6 mt-2">
        <div class="col-12">
          Corte
        </div>
        <div class="col-12 form-control text-center">
          {{deudor.corte}}
        </div>
      </div>
      <div class="col-6 mt-2">
        <div class="col-12">
          Tipo de pago
        </div>
        <div class="col-12 form-control text-center">
          {{deudor.get_tipo_pago_display}}
        </div>
      </div>
      <div class="col-6 mt-2">
        <div class="col-12">
          Año empieza
        </div>
        <div class="col-12 form-control text-center">
          {{deudor.get_anio_empieza_display}}
        </div>
      </div>
      <div class="col-6 mt-2">
        <div class="col-12">
          Quincena empieza
        </div>
        <div class="col-12 form-control text-center">
          {{deudor.get_qna_empieza_display}}
        </div>
      </div>
      <div class="col-6 mt-2">
        <div class="col-12">
          Año termina
        </div>
        <div class="col-12 form-control text-center">
          {{deudor.get_anio_termina_display}}
        </div>
      </div>
      <div class="col-6 mt-2">
        <div class="col-12">
          Quincena termina
        </div>
        <div class="col-12 form-control text-center">
          {{deudor.get_qna_termina_display}}
        </div>
      </div>
      <div class="col-6 mt-2">
        <div class="col-12">
          Estatus
        </div>
        <div class="col-12 form-control text-center">
          {{deudor.get_estatus_display}}
        </div>
      </div>
    </div>
    <div class="row col-12 mt-2">
      <div class="col-3 text-center">
        <a class="btn btn-info" href="{% url 'deudor-update' pk=deudor.pk %}">Editar</a>
      </div>
      <div class="col-3 text-center">
        <a class="btn btn-danger" href="{% url 'deudor-delete' pk=deudor.pk %}">Eliminar</a>
      </div>
      <div class="col-6 text-center">
        <a class="btn btn-info" href="{% url 'deudor-list' %}">Volver a la lista</a>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

<script>
  {% block inicio %}
      $('.boton_2').addClass('active');
  {% endblock %}
</script>
  

core/templates/core/deudor_list.html
{% extends "core/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% block headJS %}
{% endblock %}
{% block contenido %}
{% if user.is_authenticated %}
<div class="mt-2 mapa" style="padding: 10px;">
<h2>Lista de Deudores</h2>
<a class="btn btn-info" href="{% url 'deudor-create' %}">Nuevo</a>
<table class="table table-striped mt-2 text-center">
  <thead>
    <tr>
      <th class="col-3">Nombre</th>
      <th class="col-1">Corte</th>
      <th class="col-1">Tipo de Pago</th>
      <th class="col-1">Año Empieza</th>
      <th class="col-1">Qna Empieza</th>
      <th class="col-1">Año Termina</th>
      <th class="col-1">Qna Termina</th>
      <th class="col-1">Estatus</th>
      <th class="col-2">Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for deudor in deudores %}
      <tr>
        <td class="text-left">{{ deudor.nombre }}</td>
        <td>{{ deudor.corte }}</td>
        <td>{{ deudor.get_tipo_pago_display }}</td>
        <td>{{ deudor.get_anio_empieza_display }}</td>
        <td>{{ deudor.get_qna_empieza_display }}</td>
        <td>{{ deudor.get_anio_termina_display }}</td>
        <td>{{ deudor.get_qna_termina_display }}</td>
        <td>{{ deudor.get_estatus_display }}</td>
        <td>
          <a class="btn btn-info" href="{% url 'deudor-detail' pk=deudor.pk %}">Detalles</a> 
          <a class="btn btn-info" href="{% url 'deudor-update' pk=deudor.pk %}">Editar</a> 
          <a class="btn btn-danger" href="{% url 'deudor-delete' pk=deudor.pk %}">Eliminar</a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endif %}
{% endblock %}

<script>
  {% block inicio %}
      $('.boton_2').addClass('active');
  {% endblock %}
</script>
  